version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=pets
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=supersecret
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=supersecret
    depends_on:
      - mongo
  cat-app:
    build: .
    ports:
      - 8080:8080
    container_name: cat-app
    depends_on:
      - mongo
      - mongo-express
volumes:
  mongo-data:
    external:
      name: cat-mongo-data
